version: "3.2"
services:
  mysql:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/config:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
  zookeeper-server:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server